### ISSUE TITLE
Support Spark 3.0.0

### ISSUE THREAD

**Issue by duongnt** [jahstreet/spark-on-kubernetes-helm#33]
@jahstreet Just to put this under your radar as Spark 3.0.0 has just been released, with I guess better support for K8s.

https://spark.apache.org/news/spark-3-0-0-released.html

**Comment by jahstreet** [comment]
Hi @duongnt , thanks you for putting it on the table. I'm tracking it as well and excited to try it out. 1 more blocker that we have for this repo charts is the release of Livy Spark 3 support https://github.com/apache/incubator-livy/pull/289 (scala 2.12 in particular). Once we have it - we can go. In the meantime I have plans on playing with it to see if it works.

**Comment by duongnt** [comment]
@jahstreet Looks like https://github.com/apache/incubator-livy/pull/289 has just landed.

**Comment by jahstreet** [comment]
@duongnt , on it now.

**Comment by jahstreet** [comment]
Please check the progress in #39 .
