### ISSUE TITLE
Missing spark history server docker image for Spark 3.0.1

### ISSUE THREAD

**Issue by MBtech** [jahstreet/spark-on-kubernetes-helm#48]
The YAML file `spark-on-kubernetes-helm/charts/spark-cluster/values.yaml` uses the image with tag `3.0.1_2.12-hadoop_3.2.0_cloud` but that image is not present in the docker hub repo. Latest image there is with tag `3.0.0_2.12-hadoop_3.2.0_cloud`.

I think you probably forgot to push the docker image after building it.

**Comment by jahstreet** [comment]
Indeed, apologize 🤦 . BTW it lives here: https://github.com/JahstreetOrg/spark-history-server-docker/tree/spark-3.0.0 . Will push today.

**Comment by jahstreet** [comment]
Done.

**Comment by MBtech** [comment]
> Indeed, apologize 🤦 . BTW it lives here: https://github.com/JahstreetOrg/spark-history-server-docker/tree/spark-3.0.0 . Will push today.

Yeah just wanted to let you know.
