### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by idzikovsky** [jahstreet/spark-on-kubernetes-helm#63]
Hey, can you please add some licence to this project and to JahstreetOrg/spark-on-kubernetes-docker.
I can't use this project because of policies in our company. Furthermore, its not clear if I can use it at all as it's not clear if its free to use. Seems like according to [default GitHub licence](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) it isn't:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. 

Thank you.

**Comment by jahstreet** [comment]
Hi, I'll try to get to it somewhere this year, but unfortunately doesn't have enough time to constantly maintain this project. It is definitely free and I should reflect it in the licence.

**Comment by jahstreet** [comment]
Hi @idzikovsky , getting back to the project. Added the license. Please let me know if I can do anything else for you.
